@ApiGrupos_HostAddress = http://localhost:5122
@ApiGrupos_ApiKey = COLOCAR_API_KEY_AQUI

GET {{ApiGrupos_HostAddress}}/api/clientes?busca=maria&loja=10&page=1&pageSize=50
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/clientes/12345
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/consulta-vendas?dataInicio=2022-01-01&dataFim=2022-01-31
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/consulta-vendas-agregado?dataInicio=2024-01-01&dataFim=2024-01-31
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

# Validacao TRIFIL: filtrar fornecedor = TRIFIL no resultado.
# Esperado para 2026-06-10 a 2026-06-15: qtde_venda = 200, total_venda = 10795,12.
# Caso isolado: fornecedor TRIFIL, loja 7, data 2026-06-15, referencia C06244.
# Esperado: numero 50 => +1 / +109,90; numero 52 => -1 / -109,90.
# Conferencia C06244 no periodo: total_venda = 1637,05.
GET {{ApiGrupos_HostAddress}}/api/consulta-vendas-agregado?dataInicio=2026-06-10&dataFim=2026-06-15
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/estoque-lojas
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/ControleVolumes
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/consulta-entradas?dataInicio=2022-01-01&dataFim=2022-01-31
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/consulta-entradas-agregado?dataInicio=2024-01-01&dataFim=2024-01-31
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/recebimentos/crediarista/titulos?dataInicio=2026-08-01&dataFim=2026-08-20&somenteEmAberto=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/recebimentos/crediarista/clientes-resumo?dataInicio=2026-08-01&dataFim=2026-08-20&somenteEmAberto=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/recebimentos/crediarista/titulos?dataInicio=2026-07-01&dataFim=2026-07-31&tipoData=baixa&somentePagos=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/recebimentos/crediarista/clientes-resumo?dataInicio=2026-07-01&dataFim=2026-07-31&tipoData=baixa&somentePagos=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/recebimentos/crediarista/titulos?dataInicio=2026-07-01&dataFim=2026-07-31&tipoData=baixa&somentePagos=true&codCli=2656405
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/contasreceberterceiros/titulos?codCli=479410&somenteEmAberto=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/contasreceberterceiros/clientes-resumo?codCli=479410&somenteEmAberto=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###

GET {{ApiGrupos_HostAddress}}/api/contasreceberterceiros/titulos?dataInicio=2026-06-01&dataFim=2026-06-30&tipoData=vencimento&loja=10&codCobranca=401&somenteEmAberto=true
Accept: application/json
X-API-Key: {{ApiGrupos_ApiKey}}

###
