@ApiGrupos_HostAddress = http://localhost:5122

GET {{ApiGrupos_HostAddress}}/api/consulta-vendas?dataInicio=2022-01-01&dataFim=2022-01-31
Accept: application/json

###

GET {{ApiGrupos_HostAddress}}/api/consulta-vendas-agregado?dataInicio=2024-01-01&dataFim=2024-01-31
Accept: application/json

###

GET {{ApiGrupos_HostAddress}}/api/estoque-lojas
Accept: application/json

###

GET {{ApiGrupos_HostAddress}}/api/consulta-entradas?dataInicio=2022-01-01&dataFim=2022-01-31
Accept: application/json

###

GET {{ApiGrupos_HostAddress}}/api/consulta-entradas-agregado?dataInicio=2024-01-01&dataFim=2024-01-31
Accept: application/json

###
